# GitHub Pages Configuration
title: E2E-Commerce
description: Sistema completo de e-commerce com HTML, CSS e JavaScript
baseurl: "/e2e-commerce"
url: "https://SEU_USUARIO.github.io"

# Build settings
markdown: kramdown
highlighter: rouge
theme: minima

# Plugins
plugins:
  - jekyll-feed
  - jekyll-sitemap

# Exclude files from processing
exclude:
  - README.md
  - INSTALL.md
  - DEPLOY.md
  - package.json
  - .gitignore
  - .github/

# Include files
include:
  - _redirects

# Collections
collections:
  docs:
    output: true
    permalink: /:collection/:name/

# Defaults
defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "default"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
